version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: Nuget restore
- ps: ./update-version.ps1
build:
  project: MapReduce.Net.sln
  verbosity: minimal

after_build:
- dotnet pack "src\MapReduce.Net" -c %CONFIGURATION% --no-build -o artifacts

test: off

artifacts:
- path: \**\artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'
on_finish: # Done