version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: Nuget restore
- ps: ./update-version.ps1
build:
  project: MapReduce.Net.sln
  verbosity: minimal

after_build:
- dotnet pack "src\MapReduce.Net" -c %CONFIGURATION% --no-build -o artifacts

test_script:
- dotnet test test\MapReduce.Net.Test\MapReduce.Net.Test.csproj -c %CONFIGURATION%
- dotnet test test\MapReduce.Net.Benchmark\MapReduce.Net.Benchmark.csproj -c %CONFIGURATION%


artifacts:
- path: \**\*.artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'
on_finish: # Done